from __future__ import annotations

from rbsoftskkm.dto.admin import DeviceSettings, ProxyConfig, ServiceSettings, ServiceUser, UserToken
from rbsoftskkm.dto.cashier import Cashier
from rbsoftskkm.dto.correction105_taxes import Correction105Taxes
from rbsoftskkm.dto.correction_data import CorrectionData
from rbsoftskkm.dto.customer import Customer
from rbsoftskkm.dto.electronic_payment import ElectronicPayment
from rbsoftskkm.dto.enums import (
    AgentType,
    BarcodePrintText,
    BarcodeType,
    CheckTimeZone,
    CheckType,
    ConnectionMethod,
    CorrectionTypes,
    DeviceType,
    ElectronicPaymentMethod,
    FiscalizationOperationType,
    FiscalizationReasonCode,
    KmConfirmationType,
    LineStyle,
    MarkingPlannedStatus,
    MeasureOfQuantity,
    PictureAlignment,
    PrintAlignment,
    PrintFont,
    PrintLineType,
    PrintTemplateType,
    ServiceUserRole,
    ShiftState,
    SignCalculationObject,
    SignMethodCalculation,
    TaxSystem,
)
from rbsoftskkm.dto.fiscalization import FiscalizationDocument, FiscalizationParameters
from rbsoftskkm.dto.marking import CodeMarkInfo, MarkingVerifyResult
from rbsoftskkm.dto.operational_attribute import OperationalAttribute
from rbsoftskkm.dto.operations import (
    DeviceTaskInfo,
    OperationHistoryItem,
    OperationKmRow,
    OperationListItem,
    SenderInfo,
)
from rbsoftskkm.dto.payments import Payments
from rbsoftskkm.dto.positions import (
    Agent,
    BarcodeLine,
    FiscalLine,
    FractionalQuantity,
    Industry,
    Marking,
    PictureLine,
    Position,
    SeparatorLine,
    TextLine,
    Vendor,
)
from rbsoftskkm.dto.queue import DocumentHistoryItem, QueueItem, QueueTaskState
from rbsoftskkm.dto.results import (
    Backlog,
    CashDrawer,
    CheckCustomer,
    CheckDocument,
    CheckItem,
    CheckPayments,
    DataKkt,
    Device,
    DeviceListResponse,
    DocData,
    DocDataPayments,
    DocumentHeader,
    Driver,
    FiscalOutputParameters,
    FiscalResult,
    Fn,
    FnModes,
    KktLicense,
    KktStatus,
    Ofd,
    Picture,
    PrintFormBarcode,
    PrintFormLine,
    ProcessingKmResult,
    QrCheckData,
    RegData,
    RequestKmResult,
    ResponseCurrentStatus,
    ResponseTaskStatus,
    ResShiftTotal,
    ShiftCounters,
    ShiftIncome,
    ShiftListItem,
    Warnings,
)
from rbsoftskkm.dto.templates import (
    CheckTemplate,
    CheckTemplateDocument,
    CheckTemplateListItem,
    CheckTemplateParameters,
    PrintLine,
    PrintTemplate,
    TemplateItem,
    TemplateParameters,
)
from rbsoftskkm.dto.user_attribute import UserAttribute

__all__ = [
    "Agent",
    "AgentType",
    "Backlog",
    "BarcodeLine",
    "BarcodePrintText",
    "BarcodeType",
    "CashDrawer",
    "Cashier",
    "CheckCustomer",
    "CheckDocument",
    "CheckItem",
    "CheckPayments",
    "CheckTemplate",
    "CheckTemplateDocument",
    "CheckTemplateListItem",
    "CheckTemplateParameters",
    "CheckTimeZone",
    "CheckType",
    "CodeMarkInfo",
    "ConnectionMethod",
    "Correction105Taxes",
    "CorrectionData",
    "CorrectionTypes",
    "Customer",
    "DataKkt",
    "Device",
    "DeviceListResponse",
    "DeviceSettings",
    "DeviceTaskInfo",
    "DeviceType",
    "DocData",
    "DocDataPayments",
    "DocumentHeader",
    "DocumentHistoryItem",
    "Driver",
    "ElectronicPayment",
    "ElectronicPaymentMethod",
    "FiscalLine",
    "FiscalOutputParameters",
    "FiscalResult",
    "FiscalizationDocument",
    "FiscalizationOperationType",
    "FiscalizationParameters",
    "FiscalizationReasonCode",
    "Fn",
    "FnModes",
    "FractionalQuantity",
    "Industry",
    "KktLicense",
    "KktStatus",
    "KmConfirmationType",
    "LineStyle",
    "Marking",
    "MarkingPlannedStatus",
    "MarkingVerifyResult",
    "MeasureOfQuantity",
    "Ofd",
    "OperationHistoryItem",
    "OperationKmRow",
    "OperationListItem",
    "OperationalAttribute",
    "Payments",
    "Picture",
    "PictureAlignment",
    "PictureLine",
    "Position",
    "PrintAlignment",
    "PrintFont",
    "PrintFormBarcode",
    "PrintFormLine",
    "PrintLine",
    "PrintLineType",
    "PrintTemplate",
    "PrintTemplateType",
    "ProcessingKmResult",
    "ProxyConfig",
    "QrCheckData",
    "QueueItem",
    "QueueTaskState",
    "RegData",
    "RequestKmResult",
    "ResShiftTotal",
    "ResponseCurrentStatus",
    "ResponseTaskStatus",
    "SenderInfo",
    "SeparatorLine",
    "ServiceSettings",
    "ServiceUser",
    "ServiceUserRole",
    "ShiftCounters",
    "ShiftIncome",
    "ShiftListItem",
    "ShiftState",
    "SignCalculationObject",
    "SignMethodCalculation",
    "TaxSystem",
    "TemplateItem",
    "TemplateParameters",
    "TextLine",
    "UserAttribute",
    "UserToken",
    "Vendor",
    "Warnings",
]
